name: Test Azure Login with OIDC

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-login-no-ps-ubuntu:
    runs-on: ubuntu-latest
    environment: Azure-Gov-Dev
    steps:
    - name: OIDC Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        environment: 'AzureUSGovernment'
    - name: 'Get resource group with az cli action'
      run: az group list

  test-login-ps-ubuntu:
    runs-on: ubuntu-latest
    environment: Azure-Gov-Dev
    steps:
    - name: OIDC Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        environment: 'AzureUSGovernment'
        enable-AzPSSession: true
    - name: 'Get resource group with PowerShell action'
      uses: azure/powershell@v1
      with:
        inlineScript: Get-AzResourceGroup
        azPSVersion: "latest"

  test-login-no-ps-win:
    runs-on: windows-latest
    environment: Azure-Gov-Dev
    steps:
    - name: OIDC Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        environment: 'AzureUSGovernment'
    - name: 'Get resource group with az cli action'
      run: az group list

  test-login-ps-win:
    runs-on: windows-latest
    environment: Azure-Gov-Dev
    steps:
    - name: OIDC Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        environment: 'AzureUSGovernment'
        enable-AzPSSession: true
    - name: 'Get resource group with PowerShell action'
      uses: azure/powershell@v1
      with:
        inlineScript: Get-AzResourceGroup
        azPSVersion: "latest"

  # Public cloud below
  test-login-no-ps-ubuntu-public:
    runs-on: ubuntu-latest
    environment: Azure-Public-Dev
    steps:
    - name: OIDC Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: 'Get resource group with az cli action'
      run: az group list

  test-login-ps-ubuntu-public:
    runs-on: ubuntu-latest
    environment: Azure-Public-Dev
    steps:
    - name: OIDC Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - name: 'Get resource group with PowerShell action'
      uses: azure/powershell@v1
      with:
        inlineScript: Get-AzResourceGroup
        azPSVersion: "latest"

  test-login-no-ps-win-public:
    runs-on: windows-latest
    environment: Azure-Public-Dev
    steps:
    - name: OIDC Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: 'Get resource group with az cli action'
      run: az group list

  test-login-ps-win-public:
    runs-on: windows-latest
    environment: Azure-Public-Dev
    steps:
    - name: OIDC Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - name: 'Get resource group with PowerShell action'
      uses: azure/powershell@v1
      with:
        inlineScript: Get-AzResourceGroup
        azPSVersion: "latest"
